### PR TITLE
DROPSEC-2912: Fix default installation option.

### PR DESCRIPTION
**Pull request by cherouvim**
It was pointing to a non-existent option.

### CODE REVIEW

**Comment by joaocsilva** [comment]
Hi @cherouvim ,
Thank you for the PR, could you please change it to use the `minimal` by default ?
Thank you.
Best regards,
João Silva

**Comment by cherouvim** [comment]
@joaocsilva: done.

**Review by joaocsilva — APPROVED** [review]

**Comment by joaocsilva** [comment]
Great, thank you.
Best regards,
João Silva

**Comment by joaocsilva** [comment]
Hi @cherouvim ,
I commit to fix the version of the package `consolidation/annotated-command` as it breaks the configurations.
Best regards,
João Silva

**Review by joaocsilva — APPROVED** [review]

**Pull request merged**
